site_name: Abra Eyetracking
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Reference: API Reference.md
  - About: about.md
  - License: license.md

theme: readthedocs


- name: Deploy MkDocs
  uses: mhausenblas/mkdocs-deploy-gh-pages@1.14

